# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class AdditionStub(object):
  """The addition service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Addition = channel.unary_unary(
        '/add.Addition/Addition',
        request_serializer=calculator__pb2.AddRequest.SerializeToString,
        response_deserializer=calculator__pb2.AddReply.FromString,
        )


class AdditionServicer(object):
  """The addition service definition.
  """

  def Addition(self, request, context):
    """The method which takes the request and returns the response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdditionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Addition': grpc.unary_unary_rpc_method_handler(
          servicer.Addition,
          request_deserializer=calculator__pb2.AddRequest.FromString,
          response_serializer=calculator__pb2.AddReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'add.Addition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
